FROM apache/airflow:2.9.0
USER root
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir dbt-core==1.8.1 dbt-postgres==1.8.1